default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5
  timeout: 5000

development:
  <<: *default

production:
  <<: *default
  database: db/production.postgresql

test:
  <<: *default
  encoding: unicode
  database: <%= ENV["TEST_DB_NAME"] %>
