default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  host: localhost
  database: flashcard
  username: postgres
  password: pass

production:
  <<: *default
  database: db/production.postgresql

test:
  adapter: sqlite3
  database: db/test.sqlite3