development:
  secret_key_base: 206fe6c1b008d5b6d6f5441757b9448d6d2fad21a9221c22b25903c93b7cf0fdac0c8b9e12c9ca8d0fdf575f86ec2c0795218af7c704a21a4c57e34778b315e9
  bucket: "your bucket name"
  access_key_id: "your access key id"
  secret_access_key: "your secret access key"

test:
  secret_key_base: f62007f67cce916c80e94efcfb2403ef52d5398c0396c6b8df8b9305b7b50afea38b3e62e75b2761ee7e29d250ecc09e7e69ccb1826bcf9d8b20325f8d0b8a5b
  bucket: "your bucket name"
  access_key_id: "your access key id"
  secret_access_key: "your secret access key"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bucket: <%= ENV["S3_BUCKET"] %>
  access_key_id: <%= ENV["S3_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["S3_SECRET_KEY"] %>